require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisabledByDefault: false
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - bin/bundle
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'

#################### Lint ################################

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 100

Metrics/AbcSize:
  Enabled: true
  Max: 20

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Style/MixinUsage:
  Enabled: true
  Exclude:
    - bin/setup
    - bin/update

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
