AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - bin/bundle
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: true
  Max: 100
Metrics/AbcSize:
  Enabled: true
  Max: 20
Metrics/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - 'spec/**/*.rb'
Style/MixinUsage:
  Enabled: true
  Exclude:
    - bin/setup
    - bin/update
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
